export const GENRES = {
    Action: 'action',
    Arcade: 'arcade',
    Adventure: 'adventure',
    Indie: 'indie',
    RPG: 'role-playing-games-rpg',
    Puzzle: 'puzzle',
    Shooter: 'shooter',
    Platformer: 'platformer',
    Strategy: 'strategy',
    Casual: 'casual',
    Simulation: 'simulation',
    Sports: 'sports',
    Racing: 'racing',
    Multiplayer: 'massively-multiplayer',
    Fighting: 'fighting',
    Family: 'family',
    Board: 'board-games',
    Educational: 'educational',
    Card: 'card'
}